### ISSUE TITLE
something strange about the way markdown is pulling in

### ISSUE THREAD

**Issue by javaporter** [javaporter/roots-contentful-foundation#6]
In the first screenshot, the markdown from contentful is coming in quite strange. There's an `<li>` for the first item, then `<li><p>`, the ol is completely borked as well. The same exact contentful markdown works fine through middleman_contentful (see other screenshot). 

```jade
- for post in contentful.snuggle
          article.test
            date= post.date
            h1= post.title
            if post.heroImage
              img(src=asset(post.heroImage, {w: 1100, h: 1100}))
            != markdown(post.body)
```
![screenshot 2015-04-27 08 27 56](https://cloud.githubusercontent.com/assets/170182/7349586/72560926-ecb7-11e4-8225-62ab61c7a170.png)

![screenshot 2015-04-27 08 30 59](https://cloud.githubusercontent.com/assets/170182/7349630/c6343748-ecb7-11e4-96c5-4529ae7664ae.png)

**Comment by EnMod** [comment]
Haven't seen anything like this yet @javaporter , but if I do I'll add it here.

**Comment by jenius** [comment]
I would log this issue in `roots-contentful`

**Comment by javaporter** [comment]
thanks, good call: https://github.com/carrot/roots-contentful/issues/22

**Comment by javaporter** [comment]
this is a bug with marked (https://github.com/chjj/marked/issues/55), closing. To prevent, don't put one list after another
